export const  SET_CAR_PARK_DATA = 'SET_CAR_PARK_DATA';
export const  SET_CAR_PARK_PLATES_DATA = 'SET_CAR_PARK_PLATES_DATA';
export const  SET_CAR_PARK_ERROR = 'SET_CAR_PARK_ERROR';
export const  CLEAR_CAR_PARK_ERROR = 'CLEAR_CAR_PARK_ERROR';
export const LOADING_CAR_PARK_DATA = 'LOADING_CAR_PARK_DATA';
export const  SET_CAR_PARK_MESSAGE = 'SET_CAR_PARK_MESSAGE';
export const  CLEAR_CAR_PARK_MESSAGE = 'CLEAR_CAR_PARK_MESSAGE';
